
using System.Collections.Generic;

namespace Ovasoft.Cofitools.Domain.Model;

/// <summary>The interface implements navigation property of parent entity.</summary>
/// <typeparam name="TChild">The type of the child entity.</typeparam>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for IChild`1
public interface IChild<TChild>
{
    /// <summary>Gets or sets the Childs as entity list.</summary>
    /// <value>The Childs as entity list.</value>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for Childs
    public ICollection<TChild> Childs { get; set; } 
}
