
using System.Collections.Generic;

namespace BaikalNetHub.CodeFirst.Domain.Model;

/// <summary>The interface implements navigation property of parent entity.</summary>
/// <typeparam name="TChild">The type of the child entity.</typeparam>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for IChild`1
public interface IChild<TChild>
{
    /// <summary>Gets or sets the Children as entity list.</summary>
    /// <value>The Children as entity list.</value>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for Children
    public ICollection<TChild> Children { get; set; } 
}
