
namespace BaikalNetHub.CodeFirst.Domain.Model;

/// <summary>Base interface for database-mapped classes.</summary>
/// <remarks>
/// This base interface doesn't have any properties or methods, it just tells you that a class is mapped to a database.
/// IEntity&lt;TEntityId&gt;, which is a generic interface, inherits from this base interface, so any class that
/// uses IEntity&lt;TEntityId&gt; will also use interface IEntityBase. That means you don't need to check every possible implementations
/// of IEntity&lt;TEntityId&gt; when you're selecting a class, you can just check if it's an implementation of IEntityBase instead.
/// </remarks>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for IEntity
public interface IEntityBase { }


/// <summary>Generic interface for database-mapped classes.</summary>
/// <typeparam name="TEntityId">The type of the entity identifier.</typeparam>
/// <remarks>
/// IEntity&lt;TEntityId&gt; is a generic interface that's inherited from the EntityBase interface. 
/// So, any class that implements IEntity also implements EntityBase at the same time. 
/// That means you don't need to check for all possible implementations when selecting a class - you can
/// just see if it's an IEntityBase implementation.</remarks>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for IEntity`1
public interface IEntity<TEntityId>: IEntityBase where TEntityId : struct
{
    /// <summary>Gets or sets the Entity Id.</summary>
    TEntityId Id { get; set; }
}

/// <summary>The default interface for  database-mapped classes when the Id type is int.</summary>
/// <remarks>
/// IEntity is a special case of generic interface  IEntity&lt;TEntityId&gt; a that's inherited from the EntityBase interface. 
/// So, any class that implements IEntity also implements EntityBase at the same time. 
/// That means you don't need to check for all possible implementations when selecting a class - you can
/// just see if it's an IEntityBase implementation.</remarks>
/// <autogeneratedoc />
/// TODO Edit XML Comment Template for IEntity`1
public interface IEntity: IEntity<int> { }
